### ISSUE TITLE
add additional information on which juju is being used

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1101]
In the UI make a note about which juju is being used, currently the list is:

- /usr/bin/juju (apt)
- /snap/bin/juju (snap)
- /snap/bin/conjure-up.juju (conjure-up)

In the above case only the first found juju will be used, so we can make some sort of tasteful note to the user about which one is active.

**Comment by mskalka** [comment]
Seconding this as it's a little counter-intuitive at the moment. If I have a juju binary installed before I 'snap install conjure-up' I would assume it uses my juju binary (which it does), however I would also assume removing that juju binary and trying to conjure up something should fail. Since it doesn't, there should be an explanation around it in the GUI.

Obfuscating this fail safe could potentially cause issues for users that require a specific juju version as well as there is no way to tell which juju agent version is being used until the bootstrap has started.

**Comment by battlemidget** [comment]
Will be looking into not bundling juju with our snap so that would solve this issue
