### ISSUE TITLE
Constraints not met when deploying CDK

### ISSUE THREAD

**Issue by simonklb** [conjure-up/conjure-up#1123]
When deploying CDK to AWS I should, by default, end up with three worker nodes that are larger than the rest. This is the case when I'm using `juju deploy` but with `conjure-up` the worker nodes are the same instance type as the rest.

**Comment by johnsca** [comment]
The bundleplacer code is pulling the constraints [from `servicemeta` instead of `service_dict`](https://github.com/Ubuntu-Solutions-Engineering/bundle-placement/blob/master/bundleplacer/bundle.py#L73) but we're [not passing in any `metadata`](https://github.com/conjure-up/conjure-up/blob/master/conjureup/utils.py#L418) so it just [defaults](https://github.com/Ubuntu-Solutions-Engineering/bundle-placement/blob/master/bundleplacer/bundle.py#L125) to an empty dict.

I'm not sure what metadata is supposed to be being passed in or why the constraints from the service definition in the bundle would be ignored.

**Comment by battlemidget** [comment]
@simonklb building now https://code.launchpad.net/~conjure-up/+snap/conjure-up/+build/74806 should be available once thats done

**Comment by battlemidget** [comment]
@simonklb can you let us know if this did resolve the issue for you?

**Comment by simonklb** [comment]
@battlemidget confirmed fixed! 👍 thanks guys
