### ISSUE TITLE
too many machines 

### ISSUE THREAD

**Issue by lghinet** [conjure-up/conjure-up#1140]
- [ ] Is conjure-up running inside a virtual machine?
yes
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
yes 

![image](https://user-images.githubusercontent.com/12889810/30110093-813acd8e-9311-11e7-9c7a-f2bde278e039.png)

hello,
why is this creating 11 machines if i use only 6 ? 
thanks

**Comment by battlemidget** [comment]
I know one additional machine is for the juju controller (when you bootstrapped) , but we can't reproduce what you are seeing. Can you attach tarball of `~/.cache/conjure-up/`?

**Comment by johnsca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug: too many machines](https://trello.com/c/MdwTcTZU/69-bug-too-many-machines)

**Comment by johnsca** [comment]
@battlemidget The controller machine would be in a different model, so wouldn't be counted in the screenshot.  However, it does look like the number of units for both etcd and kubernetes-worker were reduced, and conjure-up did not reflect that in the final machine count.  There is some refactoring that needs to be done in [configapps/gui.py](https://github.com/conjure-up/conjure-up/blob/master/conjureup/controllers/configapps/gui.py)

**Comment by lghinet** [comment]
the. nr of machines was reduced 1 etcd instead of 3 and 2 workers instead of 3. 
juju controller its on another machine

can i remove those containers whose ips are not used by units?

**Comment by battlemidget** [comment]
Yea if no units are attached you can remove-machine

**Comment by johnsca** [comment]
On the localhost provider, it seems this also happens due to the machines being pre-created without any constraints but when the applications are deployed the placement directives are stripped but constraints left intact, which causes any applications with constraints specified (e.g., kube-worker) to create new machines rather than re-using a pre-created machine.

This stripping of placement seems to be there to prevent issues with things like sub-machine placement, but it would be worth testing if it's even needed any more.  If it is, though, (or just as an easy fix) we should just skip pre-machine creation entirely for localhost.

**Comment by Cynerva** [comment]
@battlemidget @johnsca It looks like we just had an occurrence of this reported in a CDK issue. Can you confirm?

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/433

**Comment by battlemidget** [comment]
@Cynerva yea this is same, we are reworking this code this cycle.

**Comment by battlemidget** [comment]
This has now been addressed
