### ISSUE TITLE
conjure-down fails with `LookupError: Unable to list controllers: /bin/sh: 1: None: not found`

### ISSUE THREAD

**Issue by rueberger** [conjure-up/conjure-up#1269]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ no] Is conjure-up running inside a virtual machine?
- [yes] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju:  /snap/bin/juju
juju version: 2.4-beta1-xenial-amd64

which conjure-up: /snap/bin/conjure-up
conjure-up --version: conjure-up 2.5-alpha1 

which lxc: /snap/bin/lxc
/snap/bin/lxc config show: config:
  core.https_address: '[::]'
/snap/bin/lxc version: 2.20

cat /etc/lsb-release: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1549821/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sosreport (version 3.4)

no valid plugins were enabled
```

## What Spell was Selected?

I have installed only the canonical distribution of kubernetes

## What provider (aws, maas, localhost, etc)?

localhost

## Commands ran

Please outline what commands were run to install and execute conjure-up:

Installed with snap, kubernetes installed with `conjure-up kubernetes`

The problematic command for this issue was `conjure-down`:  results in the following traceback in `~/.cache/conjure-up/conjure-down.log`

```
2017-12-11 19:17:56,703 [ERROR] conjure-up/_unspecified_spell - events.py:160 - Unhandled exception in <Task finished coro=<_start() done, defined at /snap/conjure-up/885/lib/python3.6/site-packages/conjureup/destroy.py:45> exception=LookupError('Unable to list controllers: /bin/sh: 1: None: not found\n',)>
Traceback (most recent call last):
  File "/snap/conjure-up/885/lib/python3.6/site-packages/conjureup/destroy.py", line 50, in _start
    controllers.use('destroy').render()
  File "/snap/conjure-up/885/lib/python3.6/site-packages/conjureup/controllers/destroy/gui.py", line 17, in render
    existing_controllers = juju.get_controllers()['controllers']
  File "/snap/conjure-up/885/lib/python3.6/site-packages/conjureup/juju.py", line 793, in get_controllers
    "Unable to list controllers: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list controllers: /bin/sh: 1: None: not found
```
`ls -l /bin/sh`:

```
lrwxrwxrwx 1 root root 4 Dec  9 02:08 /bin/sh -> dash
```

Could the problem be the symlink?

**Comment by johnsca** [comment]
The `sh` -> `dash` symlink seems to be the default on xenial, so that's not the issue.  It seems like the `app.juju.bin_path` is being set to `None`, i.e., conjure-up couldn't locate the Juju binary.  It should have failed sooner than this, however, if that were the case.  We need to check the validation that a Juju binary can be found.

We should also consider converting this to using `JujuData` from `libjuju` rather than shelling out to the binary for this.

**Comment by shrajfr12** [comment]
Similar issue is encountered on mac also. "Unable to list controllers: /bin/sh: None: command not found" is seen on conjure-down screen.

**Comment by rfc1459** [comment]
From a cursory glance, this issue was _probably_ introduced in #1246: `destroy.py` lacks calls to `juju.set_bin_path()` and `juju.set_wait_path()`, so `app.juju.bin_path` is still set to `None` by the time the gui tries to list controllers.

This also causes headless `conjure-down` to enter an infinite loop while trying to talk to the Juju controller (the error is the same).
