### ISSUE TITLE
Unable to deploy OpenStack on Novalxd with Ubuntu 18.04

### ISSUE THREAD

**Issue by kareemshayeb** [conjure-up/conjure-up#1440]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by julianowick** [comment]
It seems like the the installation is complaining because it needs an "IPv4-only" network, not just any network or no IPv6 at all. Installing kubernetes I faced the same issue. Disabling IPv6 in the lxd network solved the issue for me. Like this:

# lxc network set lxdbr0 ipv6.address none

--Juliano

**Comment by ColumGaynor** [comment]
CG: Thank you.

**Comment by ColumGaynor** [comment]
Tried once again tonight with different machine (older Ubuntu 16.10 running there)... Taking the snap available tonight June 12th 2018 at around 22:30pm Finnish time, I am encountering new issues.
Typing conjure-up throws python trace-back complaining that version of juju cannot be determined.
Tried to also send mail to Adam Stokes on this. Some traces shown below.

1) Installed snaps for lxd, juju and conjure-up
     (used --classic channel for conjure-up. Failed.
      also tried --edge channel for conjure-up. Failed - same reason.
2) Prior to attempting to run conjure-up - went through init procedure for lxd as guided in:
  `  https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up?_ga=2.173203299.1531852235.1528832136-964510752.1528563159#1
`
      Typing `conjure-up` give error that version of juju cannot be determined!
      See printout:

```
gaynor@gaynor-Aspire-E5-521:~$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop1    7:1    0 162,9M  1 loop /snap/spotify/16
loop8    7:8    0  54,4M  1 loop /snap/lxd/7412
loop6    7:6    0 164,6M  1 loop /snap/microk8s/55
loop4    7:4    0  86,6M  1 loop /snap/core/4650
loop2    7:2    0 162,6M  1 loop /snap/spotify/6
loop0    7:0    0  86,6M  1 loop /snap/core/4571
loop10   7:10   0  52,5M  1 loop /snap/juju/4423
sda      8:0    0 931,5G  0 disk
├─sda4   8:4    0   465G  0 part
├─sda2   8:2    0   300M  0 part /boot/efi
├─sda7   8:7    0 393,8G  0 part /home
├─sda5   8:5    0  15,9G  0 part
├─sda3   8:3    0   128M  0 part
├─sda1   8:1    0   600M  0 part
├─sda8   8:8    0   9,3G  0 part [SWAP]
└─sda6   8:6    0  46,6G  0 part /
loop5    7:5    0 162,1M  1 loop /snap/spotify/13
loop3    7:3    0  86,6M  1 loop /snap/core/4486
gaynor@gaynor-Aspire-E5-521:~$ sudo snap install conjure-up --classic
conjure-up 2.5.7-20180606.1806 from 'canonical' installed

gaynor@gaynor-Aspire-E5-521:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/1006/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.5.7', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/app.py", line 278, in main
    utils.juju_version(),
  File "/snap/conjure-up/1006/lib/python3.6/site-packages/conjureup/utils.py", line 271, in juju_version
    raise Exception("Could not determine Juju version.")
Exception: Could not determine Juju version.

gaynor@gaynor-Aspire-E5-521:~$ juju --version
2.3.8-yakkety-amd64

gaynor@gaynor-Aspire-E5-521:~$ conjure-up --version
conjure-up 2.5.7
```

    Any ideas what could be wrong ?

    Best regards Colum

**Comment by ColumGaynor** [comment]
@kareemshayeb   See issue #1475 ... I have an OpenStack now up but not fully working on Ubuntu 18.04 Desktop. You may be able to get some tips from my ûber struggle!

I have requested if @battlemidget is willing to receive more error reports and have a chance to fix them. Attempts to start conjure-up OpenStack NovaLXD fail on Ubuntu 16.04 and 16.10 (as commented above) but I think this has now been flagged separately. It would be great if Canonical could get this working for Ubuntu 16.04 and 18.04 as it is a usual demonstration of OpenStack on LXD which is surely of interest to a lot of OpenStack fans.

**Comment by alansenairj** [comment]
same for me installing openstack nova lxd on ubuntu 18.04 here. 

________________________________________________

  Where would you like to deploy?                                        

                                                                           
    ───────────────────────────────────────────────────────────────────────
                                                                           
        Configure a New Cloud                                                 │
                                                                              │
        ───────────────────────────────────────────────────────────────       │
                                                                              │
      *    localhost                                                           │
          maas                                                                █
          openstack                                                           █
          vsphere                                                             █
                                                                           
    ───────────────────────────────────────────────────────────────────────
                                                                           
     Unable to parse JSON output from LXD, does `/snap/bin/lxc query --wait
                 -X GET /1.0` return info about the LXD server?

**Comment by battlemidget** [comment]
Your LXD setup isn't complete it looks like or you're using the wrong version of LXD. Please see: https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd

**Comment by alansenairj** [comment]
Yes. LXD install was completed. I summon up an Ubuntu instance and it pinged out. I was using Ubuntu in VMWare and it has some problems to finish cause I think it was a hardware limitation. 

I´m finishing Openstack localhost install right now in real workstation hardware and the first problem was just reboot system. Before reboot LXD wake-up and conjure-up found this LXD

**Comment by Nadhirovich** [comment]
**sudo usermod -a -G lxd $USER** 
that worked for me .. to add the current user to lxd group

**Comment by enrichilversum** [comment]
Hold your horses, not stale at all :)

`enric@e6220:~$ ./fucking_commnad.sh 
which juju:     /snap/bin/juju
juju version:   2.5.0-cosmic-amd64
which conjure-up:       /snap/bin/conjure-up
conjure-up version:     conjure-up 2.6.7
which lxc:      /snap/bin/lxc
snap/bin/lxc  config show:      config: {}
snap/bin/lxc version:   Client version: 3.13
Server version: 3.13
cat etc/lsb-release     DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
`

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3194119/conjure-up.tar.gz)

Brand new, fresh install of 18.10, 16 GB and an empty 248 SSD on a Dell Latitude e6220. I have followed all the tips here. IPV6 is disabled on the router, on the Wifi settings, on lxd init and again using the above command. 

It took me some browsing to remove all the lxd stuff, specially the zfs volume for which I installed zfs-tools. 

The issue is that it's not the first time this happens, I have been fighting the install with conjure-up, devstack and packstack on CentOS 7 and I gave up because I had no spare time. The problem is that I need it installed for a certification, else I would just drop it and install OpenNebula. I managed to get it running in CentOS but I have a whole network with Ubuntu machines and I don't want to waste even more time with a different distro just for testing Openstack (this version was on a VM at work and it failed to mount instances due to lack of memory).

Any thoughts before  I drop it and say goodbye to the price of the certification? 

Thanks in advance and sorry for the drama :)
