### ISSUE TITLE
No clear instruction why LXD(localhost) provider is not available with localhost-only spells

### ISSUE THREAD

**Issue by nobuto-m** [conjure-up/conjure-up#1441]
## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.4-beta2-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.7

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
bash: /snap/bin/lxc: No such file or directory

/snap/bin/lxc version
bash: /snap/bin/lxc: No such file or directory

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2025656/conjure-up.tar.gz)

## What Spell was Selected?
openstack-novalxd (OpenStack with NovaLXD)

## What provider (aws, maas, localhost, etc)?
localhost

## Commands ran
1. $ conjure-up
1. Select "OpenStack with NovaLXD" in the UI
1. Every provider is grayed out and it doesn't tell why in the UI.
![openstack-lxd](https://user-images.githubusercontent.com/4356209/40351168-b8708d7a-5de6-11e8-87b1-38e8c378e163.png)

## Additional Information
With other non-localhost spells (e.g. kubernetes-core), it tells why properly (LXD version 3.0.0 or greater is required).
![kubernetes-core](https://user-images.githubusercontent.com/4356209/40351221-d5cc750a-5de6-11e8-9322-82ff133c5cb6.png)

Or CLI tells why as well, but this information is not available in the UI.
```
$ conjure-up openstack-novalxd localhost
[info] Summoning openstack-novalxd to localhost
[error] LXD Server or LXC client not compatible
[warning] Shutting down
```

**Comment by johnsca** [comment]
If lxd is not installed at all, then selecting openstack-novalxd results in an immediate and fatal error with info about what went wrong.  And, as noted, if any other clouds are available, the highlight works and you can see the details about why you can't select localhost.  So we need to either extend the fatal error behavior or make selection work even if no clouds can actually be selected (if the spell defines a whitelist, then choose the first item from the whitelist, otherwise just choose the first cloud).  I vote for the latter, as well as removing the fatal error behavior altogether.
