### ISSUE TITLE
Failure to bootstrap maas - apparent distribution mismatch - conjure-up sees xenial but system is bionic

### ISSUE THREAD

**Issue by christianmscott** [conjure-up/conjure-up#1516]
## Report

- [No ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [No] Is conjure-up running inside a virtual machine?
- [Yes ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version
2.4.3-bionic-amd64

which conjure-up
conjure-up --version
conjure-up 2.6.1

which lxc
/snap/bin/lxc config show
config: {}
/snap/bin/lxc version
Client version: 3.5
Server version: 3.5

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2412206/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
[sosreport-cscott-20180924175108.tar.gz](https://github.com/conjure-up/conjure-up/files/2412244/sosreport-cscott-20180924175108.tar.gz)

## What Spell was Selected?
OpenStack with NovaKVM
## What provider (aws, maas, localhost, etc)?
maas
### MAAS Users
Which version of MAAS?
2.4.2 (7034-g2f5deb8b8-0ubuntu1)
## Commands ran
conjure-up
Please outline what commands were run to install and execute conjure-up:
sudo snap install conjure-up --classic
## Additional Information

Relevant component of conjure-up.log:

```
2018-09-24 17:24:25,495 [ERROR] conjure-up/openstack-base - common.py:60 - Error bootstrapping controller: ['Creating Juju cont
roller "conjure-up-cloud-maas-24f-02c" on cloud-maas-24f', 'Looking for packaged Juju agent version 2.4.3 for amd64', 'Launchin
g controller instance(s) on cloud-maas-24f...', 'ERROR failed to bootstrap model: cannot start bootstrap instance: unexpected: 
ServerError: 400 Bad Request ({"distro_series": ["\'xenial\' is not a valid distro_series.  It should be one of: \'\', \'ubuntu
/bionic\'."]})']
```

**Comment by battlemidget** [comment]
Have you synced the cloud images in MAAS yet?

**Comment by christianmscott** [comment]
Yes

Christian Scott

616.834.2100
christianmscott@outlook.com

**Comment by battlemidget** [comment]
Odd, according to the response from MAAS to Juju (used behind the scenes) it only knows of Bionic (18.04)

```
({"distro_series": ["\'xenial\' is not a valid distro_series.  It should be one of: \'\', \'ubuntu
/bionic\'."]})']
```

I would double check to make sure that you can deploy a MAAS node with Xenial before trying to bootstrap. Keep in mind that the thing that you are deploying has a series defined, and I think by default we're still using `series: xenial` in the deployment bundle. You could potentionally get around this temporarily by creating a yaml file (`my-series.yaml`) with:

```
series: bionic
```

Then with conjure-up pass in:

```
conjure-up --bundle-add ./my-series.yaml
```

This will override the current bundles series of xenial to bionic.

**Comment by christianmscott** [comment]
Ah, so basically, Bionic is not supported for maas/conjure-up deployment yet? I built this cluster with Bionic just to try it out, but might just rebuild with Xenial.

Christian

**Comment by battlemidget** [comment]
You won't need to rebuild if you use that`conjure-up --bundle-add ./my-series.yaml`. The series in the deployments sets what the cloud images are being used. By default we set `series: xenial` but using the above change, it'll override the deployment to use bionic instead.

**Comment by pharper-or** [comment]
I have hit the same issue and the suggested workaround had no effect.  The juju bootstrap call generated by conjure-up still inserts '--bootstrap-series xenial'.  Excerpt from conjure-up.log:

2018-10-25 20:47:13,110 [DEBUG] conjure-up/openstack-base - juju.py:253 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'cloud-maas-93e', 'conjure-up-cloud-maas-93e-3fd', '--default-model', 'conjure-openstack-base-01b', '--config', 'image-stream=daily', '--to', 'ad-ostk2-2', **'--bootstrap-series', 'xenial',** '--credential', 'conjure-cloud-maas-93e-d7d']

Additionally, looking at the code pulled from GitHub from the master branch it looks like there is an issue with how the juju.bootstrap routine is called -- looks to be missing the series argument.  Excerpt from common.py showing call with four arguments:

    async def do_bootstrap(self):
        self.emit('Bootstrapping Juju controller...')
        track_event("Juju Bootstrap", "Started", "")
        cloud_with_region = app.provider.cloud
        if app.provider.region:
            cloud_with_region = '/'.join([app.provider.cloud,
                                          app.provider.region])
        success = await juju.bootstrap(app.provider.controller,
                                       cloud_with_region,
                                       app.provider.model,
                                       credential=app.provider.credential)

While the definition for the juju.bootstrap method (from juu.py) shows 5 arguments:

async def bootstrap(controller, cloud, model='conjure-up', series="xenial",
                    credential=None):

It would be nice to have a conjure-up option for '--bootstrap-series' added to be able to pass the desired series.  Since there is already a conjure-up option for '--bootstrap-to' there seems to be some precedent with adding options to pass to juju.

**Comment by shashinandan** [comment]
Any updates on this issue. @pharper-or were you able to resolve this?
I have lenovo systems that does not work with 16.04, it is not recognizing the RAID controller. I have to use 18.04 to get things going. Is there a workaround for this issue
