### ISSUE TITLE
crash in bootstrap because juju beta 16 does not allow bootstrap --upload-tools

### ISSUE THREAD

**Issue by TekunoKage** [conjure-up/conjure-up#367]
The file "conjure-up openstack crash.txt" is the terminal session.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
cat /proc/version
Linux version 4.4.0-34-generic (buildd@lgw01-20) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
```

conjure-up is already the newest version (2.0.0.6-0~201607182218~ubuntu16.04.1)
juju-2.0 is already the newest version (2.0-beta16-0ubuntu1~16.04.1~juju1)

[openstack.log.txt](https://github.com/conjure-up/conjure-up/files/438521/openstack.log.txt)
[combined.log.txt](https://github.com/conjure-up/conjure-up/files/438520/combined.log.txt)
[conjure-up openstack crash.txt](https://github.com/conjure-up/conjure-up/files/438522/conjure-up.openstack.crash.txt)

Regards,

**Comment by mikemccracken** [comment]
Sorry for the inconvenience.

This is because juju beta 16 changed the bootstrap command to not allow the '--upload-tools' argument. If you use a slightly earlier version of juju, it should work.

You can also bootstrap a controller manually then run conjure-up - if you select the same cloud type it'll try to reuse an existing controller.

We need to update the way we call bootstrap - I'll just edit this bug title and we can track that work here.

**Comment by TekunoKage** [comment]
Not necessary to apologies. I want to thank, for the good work and efforts! I will wait and track the progress.
Regards,
