### ISSUE TITLE
back button

### ISSUE THREAD

**Issue by gaughen** [conjure-up/conjure-up#572]
I'd very much like a back button, so if I make a wrong choice, I can go back and change it.  I hit this when I hit enter twice on the first screen and it flew past the second screen and then wasn't sure which cloud I was deploying to, and wasn't able to go back and change it.

**Comment by mikemccracken** [comment]
Agreed this would be nice. And it'd be easy enough for the first couple screens.
IIRC we decided in discussion with design that it's best to be consistent and since back/forward doesn't make as much sense in later screens, we left it off the first few too.

Might be worth revisiting this in light of plans for using conjure-up to revisit a previous deploy to add to it. Changes necessary to make that work could also make 'back' work throughout.

**Comment by battlemidget** [comment]
This has been fixed in recent navigation updates.
