### ISSUE TITLE
traceback in conjure-up

### ISSUE THREAD

**Issue by focaaby** [conjure-up/conjure-up#653]
I had finished `snap install conjure-up --classic --beta`

```
Traceback (most recent call last):
  File "/snap/conjure-up/54/bin/conjure-up", line 7, in <module>
    from conjureup.app import main
ImportError: No module named 'conjureup'
```

`$ snap --version`

```
snap    2.21
snapd   2.21
series  16
ubuntu  16.04
```

`$ snap list`

```
Name         Version  Rev   Developer  Notes
conjure-up   2.1.0    54    canonical  classic
lxd          2.8      976   canonical  -
ubuntu-core  16.04.1  1411  canonical  -
```

**Comment by battlemidget** [comment]
@focaaby Yea this is due to you running an older version of `ubuntu-core` (now renamed to `core`). 

You'll want to upgrade that first by doing the following:

1. edit `/etc/apt/sources.list` and append the following to that file:

`deb http://archive.ubuntu.com/ubuntu xenial-proposed main restricted universe multiverse`

2. `sudo apt-get update`
3. `sudo apt-get install -t xenial-proposed snapd`
4. Verify `snap list` reports:

```
conjure-up   2.1.0    54    canonical  classic
lxd          2.8      976   canonical  -
core  16.04.1  888  canonical  -
```

**Comment by focaaby** [comment]
@battlemidget 
After upgrading `ubuntu-core` to `core`, it works!!

Thank you very much!

**Comment by battlemidget** [comment]
np! let us know if you run into other issues.
