### ISSUE TITLE
Openstack Autopilot deployment on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by sanjaybarmeda** [conjure-up/conjure-up#851]
Environment 👍  Ubuntu Autopilot on Ubuntu 16.04 LTS with Mass 2.1.5 and Juju 2.1.2 all with latest version.
Juju bootstrap deployed on one of the nodes and also able access juju login with credentials. Now during setup it gets stuck on Haproxy, landscape, postgresql, and rabbitmq where its is showing awaiting for machine and it doesn't move forward from there.

Setup : 1 Mass server
               1 Node for Juju + Autopilot
               3 Nodes kept idle.

Kindly suggest necessary steps for troubleshooting....

**Comment by battlemidget** [comment]
Perhaps you misunderstood my email, I asked to kindly take note of the issue template and provide what we ask for to further troubleshoot this.

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
lxc config show
cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

In order to better get an overall idea of your system setup please also attach a **sosreport**

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?

## What provider (aws, maas, localhost, etc)?

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**Comment by sanjaybarmeda** [comment]
Please find below the output as required.
demo@maas:~$ which juju
/snap/bin/juju
demo@maas:~$ which conjure-up
/snap/bin/conjure-up
demo@maas:~$ which lxd
/usr/bin/lxd
demo@maas:~$ juju version
2.1.2-xenial-amd64
demo@maas:~$ conjure-up --version
conjure-up 2.1.5
demo@maas:~$ lxd --version
2.13
demo@maas:~$ lxc config show
config:
  core.https_address: '[::]:8443'
  images.auto_update_interval: "0"
demo@maas:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
-------------
Command Used to install Conjure-up:
snap install conjure-up --classic
--------------
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/970433/conjure-up.tar.gz)
-------------
Environment : 1 Node for MAAS, 1 Node for Juju and Autopilot 
-------------
demo@maas:~$ juju status
Model                  Controller           Cloud/Region  Version
conjure-landscape-fe3  conjure-up-maas-6c7  maas          2.1.2

App               Version  Status   Scale  Charm             Store       Rev  OS      Notes
haproxy                    waiting    0/1  haproxy           jujucharms   41  ubuntu  exposed
landscape-server           waiting    0/1  landscape-server  jujucharms   21  ubuntu
postgresql                 waiting    0/1  postgresql        jujucharms  101  ubuntu
rabbitmq-server            waiting    0/1  rabbitmq-server   jujucharms    5  ubuntu

Unit                Workload  Agent       Machine  Public address  Ports  Message
haproxy/0           waiting   allocating  0/lxd/0                         waiting for machine
landscape-server/0  waiting   allocating  0/lxd/1                         waiting for machine
postgresql/0        waiting   allocating  0/lxd/2                         waiting for machine
rabbitmq-server/0   waiting   allocating  0/lxd/3                         waiting for machine

Machine  State    DNS  Inst id  Series  AZ
0        down          pending  xenial
0/lxd/0  pending       pending  xenial
0/lxd/1  pending       pending  xenial
0/lxd/2  pending       pending  xenial
0/lxd/3  pending       pending  xenial

Relation     Provides          Consumes          Type
peer         haproxy           haproxy           peer
website      haproxy           landscape-server  regular
db-admin     landscape-server  postgresql        regular
amqp         landscape-server  rabbitmq-server   regular
replication  postgresql        postgresql        peer
cluster      rabbitmq-server   rabbitmq-server   peer
-----------------
haresh@maas:~$ juju gui
GUI 2.5.2 for model "admin/conjure-landscape-fe3" is enabled at:
  https://10.1.1.197:17070/gui/u/admin/conjure-landscape-fe3
Your login credential is:
  username: admin
  password: b56ce4d01730c2c073aedf79b85b85c

**Comment by battlemidget** [comment]
You don't have enough machines available to deploy Autopilot. You need a total of 6 machines as outlined at https://www.ubuntu.com/download/cloud/autopilot

**Comment by battlemidget** [comment]
Closing out as requirements are not met for Autopilot
