### ISSUE TITLE
jaas login failures

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#983]
It seems the controller name is not being prompted and throwing off the stdin inputs

**Comment by johnsca** [comment]
If I have cookies available from a previous login, the registration succeeds (as expected because it doesn't need the email, password, or 2FA) but ends up with the controller being named `jimm.jujucharms.com` rather than `jaas` as we specify.  Via debugging, the `stdout` and `stderr` are:

```
ipdb> pp stdout
''
ipdb> pp stderr
('Welcome, johnsca@external. You are now logged into "jimm.jujucharms.com".\n'
 '\n'
 'Current model set to "tvansteenburgh@external/k8s-ci".\n')
```

When I delete the cookies, it fails with the invalid email error, and debugging uncovers that the `stdout` and `stderr` have the following values:

```
ipdb> pp stdout
('Login to Ubuntu SSO\n'
 'Press return to select a default value.\n'
 'E-Mail: Password: Two-factor auth (Enter for none): ')
ipdb> pp stderr
('ERROR cannot log into "jimm.jujucharms.com": cannot get token: Invalid '
 'request data (email: [Enter a valid email address.])\n')
```

In both cases, you can see that it did not prompt for the controller name as expected.  Registering the controller manually from the CLI works as it should and prompts for the controller name:

```
[johnsca@murdoch:~/juju/conjure-up] [conjure-dev] $ juju register -B jimm.jujucharms.com
Enter a name for this controller: jaas
Login to Ubuntu SSO
Press return to select a default value.
E-Mail: <email-address>
Password: 
Two-factor auth (Enter for none): <2FA>

Welcome, johnsca@external. You are now logged into "jaas".

Current model set to "tvansteenburgh@external/k8s-ci".
```

Piping the controller name to the CLI also works as expected:

```
[johnsca@murdoch:~/juju/conjure-up] [conjure-dev] $ echo 'jaas' | juju register -B jimm.jujucharms.com
Enter a name for this controller: 
Welcome, johnsca@external. You are now logged into "jaas".

Current model set to "tvansteenburgh@external/k8s-ci".
```

So it doesn't seem to be something as simple as not working with piped `stdin`, since it works with the pipe on the CLI and it reads the other fields from the programmatic pipe just fine as well.
